steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/vertexai-search-demo", "."]

  # Step 2: Push the Docker image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/vertexai-search-demo"]

  # Step 3: Deploy the Docker image to Google Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
        "run",
        "deploy",
        "vertexai-search-demo",
        "--image",
        "gcr.io/$PROJECT_ID/vertexai-search-demo",
        "--port",
        "8000",
        "--platform",
        "managed",
        "--region",
        "asia-southeast1", # Replace with your desired region
        "--allow-unauthenticated",
      ]

images:
  - "gcr.io/$PROJECT_ID/vertexai-search-demo"

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  logging: CLOUD_LOGGING_ONLY
